### PR TITLE
CORRECT: LICENSE FILE.

### PR DESCRIPTION
**Pull request by loannaflip**
don't do license.txt. instead take this. thank you

### CODE REVIEW

**Comment by mellowagain** [comment]
Is there a reason to do this?

**Comment by loannaflip** [comment]
@Marc3842h yes.

**Comment by mellowagain** [comment]
...and that would be?

**Comment by Uniminin** [comment]
@Marc3842h your way of adding license by license.txt is wrong in github. You should add it directly from github from license options.

**Pull request closed without merging**
